function metrics = cache_reliability_matrix(hitRate, p99LatencyMs, evictionRate, incidentRate)
% hitRate, evictionRate, incidentRate in [0,1]; p99LatencyMs >= 0

    stability_score = max(0, 1.0 ...
        - 0.4 * (1 - hitRate) ...
        - 0.3 * (min(p99LatencyMs, 500) / 500.0) ...
        - 0.2 * evictionRate ...
        - 0.1 * incidentRate);

    bio_safety_index = max(0, 1.0 ...
        - 0.5 * incidentRate ...
        - 0.3 * evictionRate ...
        - 0.2 * (min(p99LatencyMs, 500) / 500.0));

    metrics = struct();
    metrics.hitRate           = hitRate;
    metrics.p99LatencyMs      = p99LatencyMs;
    metrics.evictionRate      = evictionRate;
    metrics.incidentRate      = incidentRate;
    metrics.stabilityScore    = stability_score;
    metrics.bioSafetyIndex    = bio_safety_index;
end
